### PR TITLE
Prism bukkit 235

### LINKED ISSUE #235: [BUG] Player name change throws exception
**Describe the bug**
A player who changed his name to match a previously used name caused an exception in Prism.
See https://pastebin.com/kju1czbr

**To Reproduce**
Player A joins with UUID 1
Player B joins with UUID 2
Player A renames his account to B
Player B joins with UUID 1 - Exception thrown and prism_players table is left with Player B UUID 2
(Note this occurred over a 12 month period)

**Expected behavior**
Prism should handle this as a matter of course and have the correct data in prism_players. Also note that at this point UUIDs 1 and 2 both have the same player name. prism_players should handle this properly.  (I guess lookups for the original Player B are no longer possible?)

**Server (please complete the following information):**
  - Prism Version: v2.1.7-
  - Server Type: Spigot
  - Server Version: git-Spigot-628435a-b5e5adc (MC: 1.16.4)

### PR DESCRIPTION
**Pull request by Narimm**
Closes #235

### CODE REVIEW

File: src/main/java/me/botsko/prism/players/PlayerIdentification.java [hunk 1]
```diff
@@ -118,12 +119,15 @@ private static PrismPlayer getPrismPlayer(UUID uuid, String name) {
...
         // Lookup by UUID
         prismPlayer = lookupByUuid(uuid);
+        // does the name match
         if (prismPlayer != null) {
             return prismPlayer;
         }
 
         // Still not found, try looking them up by name
         prismPlayer = lookupByName(name);
+        // now check if the uuid is the same as the one logging in ...if it isnt we likely need to
```
Comment (viveleroi) [inline src/main/java/me/botsko/prism/players/PlayerIdentification.java]: This comment implies logic is running here but it's just a return?

File: src/main/resources/languages/message.properties [hunk 2]
```diff
@@ -254,4 +254,6 @@ command-view-chunks=Showing current chunk boundaries.
 preview-pending=You have an existing preview pending. Please apply or cancel before moving on.
 preview-none-pending=You have no preview pending.
 preview-worldedit-unsupported=Prism does not support previews for WorldEdit rollbacks/restores yet.
-alert-prefix=[!]
\ No newline at end of file
+alert-prefix=[!]
+changed\ gamemode=changed gamemode
```
Comment (viveleroi) [inline src/main/resources/languages/message.properties]: Why use gamemode as two words *and* as one?
